# 타임리프 설정 (새로고침으로 변경사항 바로 반영)
spring.thymeleaf.cache=false

# 메시지 설정
spring.messages.basename=messages,errors

# DB 설정
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.jdbc-url=jdbc:mysql://localhost:3306/community?useSSL=false&serverTimezone=Asia/Seoul

# 매퍼 쿼리 로그
logging.level.com.boardcore.dao=debug